//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YrsWeb.Lib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationPayment
    {
        public int ApplicationId { get; set; }
        public int PaymentSeq { get; set; }
        public byte PaymentStatus { get; set; }
        public System.DateTime InsertDate { get; set; }
        public string ShopID { get; set; }
        public string JobCd { get; set; }
        public int Amount { get; set; }
        public int Tax { get; set; }
        public string Currency { get; set; }
        public string AccessID { get; set; }
        public string AccessPass { get; set; }
        public string OrderID { get; set; }
        public string TranID { get; set; }
        public string TranDate { get; set; }
        public string CheckString { get; set; }
        public string ErrCode { get; set; }
        public string ErrInfo { get; set; }
        public string ClientField1 { get; set; }
        public string ClientField2 { get; set; }
        public string ClientField3 { get; set; }
    }
}
