//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YrsWeb.Lib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationUser
    {
        public int ApplicationId { get; set; }
        public int UserNo { get; set; }
        public string UserName1 { get; set; }
        public string UserName2 { get; set; }
        public string UserRuby1 { get; set; }
        public string UserRuby2 { get; set; }
        public string ZipCode { get; set; }
        public string UserAddress1 { get; set; }
        public string UserAddress2 { get; set; }
        public string UserAddress3 { get; set; }
        public System.DateTime BirthDate { get; set; }
        public byte Age { get; set; }
        public string UserPhone1 { get; set; }
        public string UserPhone2 { get; set; }
        public string UserMailAddress { get; set; }
        public byte Sex { get; set; }
        public System.DateTime InsertDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public bool DeleteFlg { get; set; }
    }
}
