//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YrsWeb.Lib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationHeader
    {
        public int ApplicationId { get; set; }
        public byte ApplicationStatus { get; set; }
        public byte PaymentMethods { get; set; }
        public short Num_Adult { get; set; }
        public short Num_Child { get; set; }
        public short Num_Infant { get; set; }
        public byte Transportation { get; set; }
        public string CheckInTime { get; set; }
        public string PointCardNo { get; set; }
        public bool PointCardFlg { get; set; }
        public System.DateTime InsertDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public bool DeleteFlg { get; set; }
        public int Amount { get; set; }
        public string OrderNo { get; set; }
    }
}
