//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YrsWeb.Lib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category_M
    {
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
        public byte CategoryLevel { get; set; }
    }
}
