//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YrsWeb.Lib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager_M
    {
        public string ManagerId { get; set; }
        public string ManagerPassword { get; set; }
        public string MailAddress { get; set; }
        public string SMTP_ServerAddress { get; set; }
        public string SMTP_Port { get; set; }
        public string SMTP_User { get; set; }
        public string SMTP_Password { get; set; }
    }
}
