//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YrsWeb.Lib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassResetRequest
    {
        public int RequestID { get; set; }
        public System.DateTime RequestDateTime { get; set; }
        public System.DateTime ExpirationDateTime { get; set; }
        public byte RequestType { get; set; }
        public byte RequestStatus { get; set; }
        public string MailAddress { get; set; }
        public string AuthCode { get; set; }
    }
}
