//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YrsWeb.Lib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanAppInfo
    {
        public int ApplicationId { get; set; }
        public int PlanId { get; set; }
        public string ProviderId { get; set; }
        public byte PublicStatus { get; set; }
        public string PlanTitle { get; set; }
        public System.DateTime PlanStartDate { get; set; }
        public System.DateTime PlanEndDate { get; set; }
        public string PlanAddress { get; set; }
        public string Access { get; set; }
        public string Overview { get; set; }
        public string Contents { get; set; }
        public int Plan_Fee_Adult { get; set; }
        public int Plan_Fee_Child { get; set; }
        public int Plan_Fee_Infant { get; set; }
        public string MeetingPlace { get; set; }
        public string TimeRequired { get; set; }
        public Nullable<short> MaxApplicantsNum { get; set; }
        public string PlanCourse { get; set; }
        public bool HiddenFlg { get; set; }
        public string CancelPolicy { get; set; }
        public Nullable<bool> AllPersonFlg { get; set; }
        public byte ApplicationStatus { get; set; }
        public byte PaymentMethods { get; set; }
        public int UserNo { get; set; }
        public string UserName1 { get; set; }
        public string UserName2 { get; set; }
        public string UserRuby1 { get; set; }
        public string UserRuby2 { get; set; }
        public string ZipCode { get; set; }
        public string UserAddress1 { get; set; }
        public string UserAddress2 { get; set; }
        public string UserAddress3 { get; set; }
        public System.DateTime BirthDate { get; set; }
        public byte Age { get; set; }
        public string UserPhone1 { get; set; }
        public string UserPhone2 { get; set; }
        public string UserMailAddress { get; set; }
        public byte Sex { get; set; }
        public System.DateTime AcceptDate { get; set; }
        public short Num_Adult { get; set; }
        public short Num_Child { get; set; }
        public short Num_Infant { get; set; }
        public int Fee_Adult { get; set; }
        public int Fee_Child { get; set; }
        public int Fee_Infant { get; set; }
        public byte Transportation { get; set; }
        public string CheckInTime { get; set; }
        public string PointCardNo { get; set; }
        public bool PointCardFlg { get; set; }
        public int Amount { get; set; }
    }
}
