//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YrsWeb.Lib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanInfo
    {
        public int PlanId { get; set; }
        public string ProviderId { get; set; }
        public byte PublicStatus { get; set; }
        public string PlanTitle { get; set; }
        public System.DateTime PlanStartDate { get; set; }
        public System.DateTime PlanEndDate { get; set; }
        public Nullable<System.DateTime> PublicStartDate { get; set; }
        public Nullable<System.DateTime> PublicEndDate { get; set; }
        public string PlanAddress { get; set; }
        public string Access { get; set; }
        public string Overview { get; set; }
        public string Contents { get; set; }
        public int Fee_Adult { get; set; }
        public int Fee_Child { get; set; }
        public int Fee_Infant { get; set; }
        public bool DeleteFlg { get; set; }
        public string MeetingPlace { get; set; }
        public string TimeRequired { get; set; }
        public Nullable<short> MaxApplicantsNum { get; set; }
        public string PlanCourse { get; set; }
        public bool HiddenFlg { get; set; }
        public string CancelPolicy { get; set; }
        public Nullable<bool> AllPersonFlg { get; set; }
    }
}
